const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const readJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const S={
 provider:localStorage.novaProvider||'local',key:localStorage.novaKey||'',model:localStorage.novaModel||'gemini-2.5-flash',
 messages:readJSON('novaMessages',[]),memory:readJSON('novaMemory',[]),notes:readJSON('novaNotes',[]),
 knowledge:readJSON('novaKnowledge',[]),tasks:readJSON('novaTasks',[]),activity:readJSON('novaActivity',[]),
 permissions:{web:false,github:false,email:false,calendar:false,automation:false,...readJSON('novaPermissions',{})},
 theme:localStorage.novaTheme||'dark',timers:readJSON('novaTimers',[])
};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){for(const k of ['messages','memory','notes','knowledge','tasks','activity','permissions','timers'])localStorage.setItem('nova'+k[0].toUpperCase()+k.slice(1),JSON.stringify(S[k]));localStorage.novaProvider=S.provider;localStorage.novaModel=S.model;localStorage.novaTheme=S.theme}
function log(action,detail=''){S.activity.unshift({time:new Date().toLocaleString(),action,detail});S.activity=S.activity.slice(0,300);save();renderActivity()}
function render(){renderMessages();renderMemory();renderKnowledge();renderTasks();renderActivity();renderHistory();renderPermissions();renderNotes();renderTimers();updateClock();applyTheme()}
function renderMessages(){const b=$('#messages');if(!b)return;b.innerHTML=S.messages.slice(-100).map(m=>'<div class="msg '+esc(m.role)+'">'+esc(m.text)+'</div>').join('');b.scrollTop=b.scrollHeight}
function renderMemory(){const x=$('#memories');if(!x)return;x.innerHTML=S.memory.map((m,i)=>'<div class="memory"><span>'+esc(m)+'</span><button data-forget="'+i+'">Forget</button></div>').join('');x.querySelectorAll('[data-forget]').forEach(b=>b.onclick=()=>{S.memory.splice(+b.dataset.forget,1);save();renderMemory();log('Memory forgotten')})}
function renderKnowledge(){const x=$('#knowledgeList');if(!x)return;x.innerHTML=S.knowledge.map((m,i)=>'<div class="memory"><span>'+esc(m)+'</span><button data-kdel="'+i+'">Delete</button></div>').join('');x.querySelectorAll('[data-kdel]').forEach(b=>b.onclick=()=>{S.knowledge.splice(+b.dataset.kdel,1);save();renderKnowledge();log('Knowledge deleted')})}
function renderTasks(){const x=$('#taskList');if(!x)return;x.innerHTML=S.tasks.map((t,i)=>'<div class="memory"><label><input type="checkbox" '+(t.done?'checked':'')+' data-tog="'+i+'"> <span>'+esc(t.text)+'</span></label><button data-tdel="'+i+'">Delete</button></div>').join('');x.querySelectorAll('[data-tog]').forEach(b=>b.onchange=()=>{S.tasks[+b.dataset.tog].done=b.checked;save();log('Task updated',S.tasks[+b.dataset.tog].text)});x.querySelectorAll('[data-tdel]').forEach(b=>b.onclick=()=>{S.tasks.splice(+b.dataset.tdel,1);save();renderTasks();log('Task deleted')})}
function renderNotes(){const x=$('#notesList');if(!x)return;x.innerHTML=S.notes.map((n,i)=>'<div class="memory"><span>'+esc(n)+'</span><button data-ndel="'+i+'">Delete</button></div>').join('');x.querySelectorAll('[data-ndel]').forEach(b=>b.onclick=()=>{S.notes.splice(+b.dataset.ndel,1);save();renderNotes();log('Note deleted')})}
function renderTimers(){const x=$('#timerList');if(!x)return;x.innerHTML=S.timers.map((t,i)=>'<div class="memory"><span>'+esc(t.label)+' — '+new Date(t.when).toLocaleString()+'</span><button data-tdel2="'+i+'">Cancel</button></div>').join('');x.querySelectorAll('[data-tdel2]').forEach(b=>b.onclick=()=>{clearTimeout(S.timers[+b.dataset.tdel2].id);S.timers.splice(+b.dataset.tdel2,1);save();renderTimers();log('Timer cancelled')})}
function renderActivity(){const x=$('#activityList');if(!x)return;x.innerHTML=S.activity.slice(0,120).map(a=>'<div class="memory">'+esc(a.time+' — '+a.action+(a.detail?' — '+a.detail:''))+'</div>').join('')}
function renderHistory(){const x=$('#historyList');if(!x)return;x.innerHTML=S.messages.length?'<p>'+S.messages.length+' messages in this conversation.</p><button id="historyExport">Export conversation</button>':'<p>No conversation yet.</p>';$('#historyExport')?.addEventListener('click',()=>download('nova-conversation.json',JSON.stringify(S.messages,null,2)))}
function renderPermissions(){const x=$('#permissionList');if(!x)return;x.innerHTML=Object.entries(S.permissions).map(([k,v])=>'<label class="memory"><span>'+esc(k)+'</span><input type="checkbox" data-perm="'+esc(k)+'" '+(v?'checked':'')+'></label>').join('');x.querySelectorAll('[data-perm]').forEach(b=>b.onchange=()=>{S.permissions[b.dataset.perm]=b.checked;save();log('Permission changed',b.dataset.perm+': '+b.checked)})}
function msg(role,text){S.messages.push({role,text,time:Date.now()});save();renderMessages();if(role==='nova'&&localStorage.novaAutoSpeak==='1')speak(text)}
function download(name,data,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function safeCalc(x){if(!/^[0-9+\-*/().%\s]+$/.test(x))throw Error('Only arithmetic is allowed');return Function('"use strict";return ('+x+')')()}
function localBrain(t){const q=t.trim();if(/^remember that /i.test(q)){const m=q.replace(/^remember that /i,'').trim();if(m){S.memory.push(m);save();renderMemory();log('Memory added',m);return'I’ll remember that: '+m}}if(/^calculate /i.test(q))try{return String(safeCalc(q.slice(10)))}catch{return'Invalid calculation.'}if(/what can you do|capabilities/i.test(q))return'I can chat with Gemini, remember things, search the web, inspect files/images, calculate, analyze CSV, manage tasks/timers, use voice, inspect public GitHub repositories, generate calendar files and mail drafts, and keep an activity log.';if(/who are you/i.test(q))return'I’m Nova — your modular personal AI workspace.';if(/how do you work/i.test(q))return'I route your request through a local tool layer first and Gemini when connected. Memory, files, tasks and settings stay in your browser unless a connected provider is used.';return'Local mode is working. Connect Gemini in Settings for full natural-language answers.'}
async function geminiText(t){const contents=S.messages.slice(-30).map(m=>({role:m.role==='user'?'user':'model',parts:[{text:m.text}]}));contents.push({role:'user',parts:[{text:t}]});const prompt='You are Nova, a capable personal AI. Be useful and honest. You have browser-local tools exposed by the app; never claim an external action happened unless the UI reports success. Known memory:\\n'+S.memory.join('\\n- ')+'\\nKnowledge:\\n'+S.knowledge.join('\\n- ');const body={system_instruction:{parts:[{text:prompt}]},contents};return geminiRequest(body)}
async function geminiRequest(body){if(!S.key)throw Error('No Gemini API key configured');const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(S.model)+':generateContent?key='+encodeURIComponent(S.key),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error?.message||('Provider error '+r.status));return j.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'No response.'}
async function send(t){t=t.trim();if(!t)return;msg('user',t);$('#input').value='';let r;try{r=S.provider==='gemini'&&S.key?await geminiText(t):localBrain(t)}catch(e){r='Nova provider error: '+e.message}msg('nova',r);log('Conversation turn')}
function speak(t){if(!('speechSynthesis'in window)){alert('Speech output is unavailable.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=Number($('#rate')?.value||1);speechSynthesis.speak(u);log('Speech output')}
function listen(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){alert('Speech recognition is unavailable in this browser.');return}const r=new R();r.lang='en-IN';r.interimResults=false;r.onresult=e=>{$('#input').value=e.results[0][0].transcript;send($('#input').value)};r.onerror=e=>alert('Voice input: '+e.error);r.start();log('Voice listening started')}
function applyTheme(){document.documentElement.dataset.theme=S.theme}
function updateClock(){if($('#clock'))$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function csvParse(s){const rows=[];let row=[],cell='',q=false;for(let i=0;i<s.length;i++){const c=s[i],n=s[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\\n'||c==='\\r')&&!q){if(c==='\\r'&&n==='\\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function csvReport(text){const rows=csvParse(text),head=rows.shift()||[],out=['Rows: '+rows.length,'Columns: '+head.length,'Columns: '+head.join(', ')];head.forEach((h,idx)=>{const vals=rows.map(r=>r[idx]).filter(v=>v!==undefined);const nums=vals.map(Number).filter(Number.isFinite);if(nums.length>1){const sum=nums.reduce((a,b)=>a+b,0);out.push(h+': numeric='+nums.length+', min='+Math.min(...nums)+', max='+Math.max(...nums)+', avg='+(sum/nums.length).toFixed(2))}});return out.join('\\n')}
async function analyzeImage(file){const b64=await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result.split(',')[1]);fr.onerror=rej;fr.readAsDataURL(file)});if(!S.key)return'Image preview is working. Add a Gemini key to enable image reasoning.';const mime=file.type||'image/jpeg';return geminiRequest({contents:[{role:'user',parts:[{text:'Analyze this image carefully. Describe visible content, text if readable, layout, objects and any useful details. Do not invent unreadable text.'},{inline_data:{mime_type:mime,data:b64}}]}]})}
async function webSearch(q){if(!q.trim())return;$('#webOut').textContent='Searching…';try{const u='https://en.wikipedia.org/w/api.php?action=opensearch&search='+encodeURIComponent(q)+'&limit=8&namespace=0&format=json&origin=*';const r=await fetch(u);if(!r.ok)throw Error('Search failed');const j=await r.json();const items=(j[1]||[]).map((t,i)=>t+' — '+(j[3]?.[i]||'')).join('\\n');$('#webOut').textContent=items||'No results.';log('Web search',q)}catch(e){$('#webOut').textContent='Web search error: '+e.message}}
async function githubRepo(){const repo=$('#repo').value.trim();if(!repo)return alert('Enter owner/repository');$('#githubOut').textContent='Loading…';try{const r=await fetch('https://api.github.com/repos/'+repo);const j=await r.json();if(!r.ok)throw Error(j.message||'Repository not found');$('#githubOut').textContent=JSON.stringify({name:j.full_name,description:j.description,stars:j.stargazers_count,forks:j.forks_count,language:j.language,default_branch:j.default_branch,url:j.html_url},null,2);log('GitHub repository read',repo)}catch(e){$('#githubOut').textContent='GitHub error: '+e.message}}
async function githubContents(){const repo=$('#repo').value.trim(),path=($('#repoPath').value||'').trim();if(!repo)return alert('Enter owner/repository');$('#githubOut').textContent='Loading…';try{const r=await fetch('https://api.github.com/repos/'+repo+'/contents/'+path);const j=await r.json();if(!r.ok)throw Error(j.message||'Unable to read contents');if(Array.isArray(j)){$('#githubOut').textContent=j.map(x=>x.type+'  '+x.path).join('\\n')}else if(j.encoding==='base64'){$('#githubOut').textContent=decodeURIComponent(escape(atob(j.content.replace(/\\n/g,''))))}else $('#githubOut').textContent=j.download_url||j.html_url;log('GitHub contents read',repo+'/'+path)}catch(e){$('#githubOut').textContent='GitHub error: '+e.message}}
function addTask(){const v=$('#taskIn').value.trim();if(!v)return;S.tasks.push({text:v,done:false});$('#taskIn').value='';save();renderTasks();log('Task added',v)}
function setTimer(){const mins=Math.max(0,Number($('#timerMinutes').value));const label=$('#timerLabel').value.trim()||'Nova timer';if(!Number.isFinite(mins))return;const when=Date.now()+mins*60000;const timer={label,when,id:null};timer.id=setTimeout(()=>{alert('Nova: '+label);if('Notification'in window&&Notification.permission==='granted')new Notification('Nova timer',{body:label});S.timers=S.timers.filter(t=>t!==timer);save();renderTimers();log('Timer fired',label)},mins*60000);S.timers.push(timer);save();renderTimers();log('Timer created',label)}
function requestNotify(){if('Notification'in window)Notification.requestPermission().then(x=>log('Notification permission',x))}
function makeICS(){const title=$('#calTitle').value.trim()||'Nova event',start=new Date($('#calStart').value||Date.now()),end=new Date(start.getTime()+60*60000),fmt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\\.\\d{3}/,'');const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Nova//EN','BEGIN:VEVENT','UID:'+Date.now()+'@nova','DTSTAMP:'+fmt(new Date()),'DTSTART:'+fmt(start),'DTEND:'+fmt(end),'SUMMARY:'+title,'END:VEVENT','END:VCALENDAR'].join('\\r\\n');download('nova-event.ics',ics,'text/calendar');log('Calendar file generated',title)}
function makeMail(){const to=$('#mailTo').value.trim(),subject=$('#mailSubject').value.trim(),body=$('#mailBody').value;location.href='mailto:'+encodeURIComponent(to)+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);log('Mail draft opened',to)}
function exportMemory(){download('nova-memory.json',JSON.stringify(S.memory,null,2))}
function fileRead(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsText(file)})}
function stageFiles(files){const x=$('#fileList');if(!x)return;x.innerHTML='';[...files].forEach(f=>{const d=document.createElement('div');d.className='memory';d.textContent=f.name+' — '+Math.round(f.size/1024)+' KB';x.append(d)});log('Files staged',files.length+' file(s)')}
$('#form')?.addEventListener('submit',e=>{e.preventDefault();send($('#input').value)});
$('#new')?.addEventListener('click',()=>{S.messages=[];save();render();log('New conversation')});
$('.jump').forEach(b=>b.addEventListener('click',()=>{$('.nav').forEach(x=>x.classList.remove('active'));const v=b.dataset.v;$('.view').forEach(x=>x.classList.remove('active'));$('#'+v)?.classList.add('active');$('#title').textContent=v==='settings'?'Settings':v}));
$('.nav').forEach(b=>b.addEventListener('click',()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.v)?.classList.add('active');$('#title').textContent=b.textContent.trim()}));
$$('[data-prompt]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.prompt)));
$('#voice')?.addEventListener('click',listen);$('#voiceStart')?.addEventListener('click',listen);$('#voiceLast')?.addEventListener('click',()=>{const m=[...S.messages].reverse().find(x=>x.role==='nova');if(m)speak(m.text)});
$('#remember')?.addEventListener('click',()=>{const v=$('#memIn').value.trim();if(v){S.memory.push(v);$('#memIn').value='';save();renderMemory();log('Memory added',v)}});
$('#exportMemory')?.addEventListener('click',exportMemory);
$('#saveKnowledge')?.addEventListener('click',()=>{const v=$('#knowledgeIn').value.trim();if(v){S.knowledge.push(v);$('#knowledgeIn').value='';save();renderKnowledge();log('Knowledge added')}});
$('#calcBtn')?.addEventListener('click',()=>{try{$('#calcOut').textContent=safeCalc($('#calc').value);log('Calculation run')}catch(e){$('#calcOut').textContent=e.message}});
$('#noteBtn')?.addEventListener('click',()=>{const v=$('#note').value.trim();if(v){S.notes.push(v);$('#note').value='';save();renderNotes();log('Note saved',v)}});
$('#exportAll')?.addEventListener('click',()=>download('nova-workspace.json',JSON.stringify({...S,key:undefined},null,2)));
$('#importAll')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const fr=new FileReader();fr.onload=()=>{try{const d=JSON.parse(fr.result);for(const k of ['messages','memory','notes','knowledge','tasks','activity','permissions'])if(d[k]!==undefined)S[k]=d[k];save();render();log('Workspace imported')}catch{alert('Invalid workspace file')}};fr.readAsText(f)});
$('#fileInput')?.addEventListener('change',e=>stageFiles(e.target.files));
$('#visionFile')?.addEventListener('change',async e=>{const f=e.target.files[0],x=$('#visionPreview');if(!f)return;x.innerHTML='';const im=new Image();im.src=URL.createObjectURL(f);im.style.maxWidth='100%';im.style.maxHeight='360px';im.style.borderRadius='14px';x.append(im);log('Image staged',f.name);if(S.provider==='gemini'&&S.key){x.insertAdjacentHTML('beforeend','<p>Analyzing with Nova…</p>');try{x.lastChild.textContent=await analyzeImage(f)}catch(err){x.lastChild.textContent='Vision error: '+err.message}}});
$('#analyzeCode')?.addEventListener('click',async()=>{const c=$('#codeIn').value;if(!c)return;let out='Local scan: '+c.split('\\n').length+' lines, '+c.length+' characters.';if(S.provider==='gemini'&&S.key)try{out+='\\n\\nAI review:\\n'+await geminiText('Review this code for bugs, security issues and improvements. Be concrete.\\n\\n'+c)}catch(e){out+='\\nAI review unavailable: '+e.message}$('#codeOut').textContent=out;log('Code analyzed locally')});
$('#addTask')?.addEventListener('click',addTask);
$('#clearHistory')?.addEventListener('click',()=>{if(confirm('Clear conversation?')){S.messages=[];save();render();log('Conversation cleared')}});
$('#save')?.addEventListener('click',()=>{S.provider=$('#provider').value;S.key=$('#key').value.trim();S.model=$('#model').value.trim()||'gemini-2.5-flash';localStorage.novaProvider=S.provider;localStorage.novaKey=S.key;localStorage.novaModel=S.model;$('#status').textContent=S.provider==='gemini'?'Gemini connected':'Local mode';log('Provider settings changed',S.provider)});
$('#forget')?.addEventListener('click',()=>{$('#key').value='';S.key='';localStorage.removeItem('novaKey');log('Gemini key forgotten')});
$('#resetPermissions')?.addEventListener('click',()=>{S.permissions={web:false,github:false,email:false,calendar:false,automation:false};save();renderPermissions();log('Permissions reset')});
$('#webSearch')?.addEventListener('click',()=>webSearch($('#webQuery').value));
$('#githubInfo')?.addEventListener('click',githubRepo);$('#githubContents')?.addEventListener('click',githubContents);
$('#timerBtn')?.addEventListener('click',setTimer);$('#notifyBtn')?.addEventListener('click',requestNotify);
$('#calendarBtn')?.addEventListener('click',makeICS);$('#mailBtn')?.addEventListener('click',makeMail);
$('#dataFile')?.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;const t=await fileRead(f);$('#dataOut').textContent=f.name.toLowerCase().endsWith('.csv')?csvReport(t):'Loaded '+f.name+' ('+t.length+' characters). For JSON: '+(t.trim().startsWith('{')||t.trim().startsWith('[')?'valid JSON candidate':'text data');log('Data file analyzed',f.name)});
$('[data-info]').forEach(b=>b.addEventListener('click',()=>alert('Nova adapter status: this panel is functional locally. External provider actions require credentials/permission; the app will not fake a successful external action.')));\n$('#themeBtn')?.addEventListener('click',()=>{S.theme=S.theme==='dark'?'light':'dark';save();applyTheme();log('Theme changed',S.theme)});
$('#autoSpeak')?.addEventListener('change',e=>{localStorage.novaAutoSpeak=e.target.checked?'1':'0';log('Auto speech',String(e.target.checked))});
window.addEventListener('error',e=>{console.error(e.error||e.message);if($('#status'))$('#status').textContent='Ready'});
window.addEventListener('unhandledrejection',e=>console.error(e.reason));
function restoreTimers(){const now=Date.now();S.timers=S.timers.filter(t=>t.when>now);S.timers.forEach(t=>{t.id=setTimeout(()=>{alert('Nova: '+t.label);if('Notification'in window&&Notification.permission==='granted')new Notification('Nova timer',{body:t.label});S.timers=S.timers.filter(x=>x!==t);save();renderTimers();log('Timer fired',t.label)},Math.max(0,t.when-Date.now()))});save()}\napplyTheme();restoreTimers();if($('#provider'))$('#provider').value=S.provider;if($('#key'))$('#key').value=S.key;if($('#model'))$('#model').value=S.model;if($('#autoSpeak'))$('#autoSpeak').checked=localStorage.novaAutoSpeak==='1';setInterval(updateClock,1000);render();
