const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const S={provider:localStorage.novaProvider||'local',key:localStorage.novaKey||'',model:localStorage.novaModel||'gemini-2.5-flash',messages:JSON.parse(localStorage.novaMessages||'[]'),memory:JSON.parse(localStorage.novaMemory||'[]'),notes:JSON.parse(localStorage.novaNotes||'[]'),knowledge:JSON.parse(localStorage.novaKnowledge||'[]'),tasks:JSON.parse(localStorage.novaTasks||'[]'),activity:JSON.parse(localStorage.novaActivity||'[]'),permissions:JSON.parse(localStorage.novaPermissions||'null')||{web:false,github:false,email:false,calendar:false,automation:false};
function save(){localStorage.novaMessages=JSON.stringify(S.messages);localStorage.novaMemory=JSON.stringify(S.memory);localStorage.novaNotes=JSON.stringify(S.notes);localStorage.novaKnowledge=JSON.stringify(S.knowledge);localStorage.novaTasks=JSON.stringify(S.tasks);localStorage.novaActivity=JSON.stringify(S.activity);localStorage.novaPermissions=JSON.stringify(S.permissions)}
function log(action,detail=''){S.activity.unshift({time:new Date().toLocaleString(),action,detail});S.activity=S.activity.slice(0,200);save();renderActivity()}
function render(){renderMessages();renderMemory();renderKnowledge();renderTasks();renderActivity();renderHistory();renderPermissions();updateClock()}
function renderMessages(){let b=$('#messages');if(!b)return;b.innerHTML='';S.messages.slice(-80).forEach(m=>{let d=document.createElement('div');d.className='msg '+m.role;d.textContent=m.text;b.append(d)});b.scrollTop=b.scrollHeight}
function renderMemory(){let x=$('#memories');if(!x)return;x.innerHTML='';S.memory.forEach((m,i)=>{let d=document.createElement('div');d.className='memory';d.innerHTML='<span></span><button>Forget</button>';d.firstChild.textContent=m;d.lastChild.onclick=()=>{S.memory.splice(i,1);save();log('Memory forgotten',m);render()};x.append(d)})}
function renderKnowledge(){let x=$('#knowledgeList');if(!x)return;x.innerHTML='';S.knowledge.forEach((m,i)=>{let d=document.createElement('div');d.className='memory';d.innerHTML='<span></span><button>Delete</button>';d.firstChild.textContent=m;d.lastChild.onclick=()=>{S.knowledge.splice(i,1);save();renderKnowledge();log('Knowledge deleted')};x.append(d)})}
function renderTasks(){let x=$('#taskList');if(!x)return;x.innerHTML='';S.tasks.forEach((t,i)=>{let d=document.createElement('div');d.className='memory';d.innerHTML='<label><input type="checkbox"> <span></span></label><button>Delete</button>';d.querySelector('span').textContent=t.text;d.querySelector('input').checked=!!t.done;d.querySelector('input').onchange=e=>{t.done=e.target.checked;save();log('Task updated',t.text)};d.querySelector('button').onclick=()=>{S.tasks.splice(i,1);save();renderTasks();log('Task deleted',t.text)};x.append(d)})}
function renderActivity(){let x=$('#activityList');if(!x)return;x.innerHTML='';S.activity.slice(0,100).forEach(a=>{let d=document.createElement('div');d.className='memory';d.textContent=a.time+' — '+a.action+(a.detail?' — '+a.detail:'');x.append(d)})}
function renderHistory(){let x=$('#historyList');if(!x)return;x.innerHTML=S.messages.length?'<p>Current conversation contains '+S.messages.length+' messages.</p><button id="historyExport">Export conversation</button>':'<p>No conversation yet.</p>';$('#historyExport')?.addEventListener('click',()=>download('nova-conversation.json',JSON.stringify(S.messages,null,2)))}
function renderPermissions(){let x=$('#permissionList');if(!x)return;x.innerHTML='';Object.entries(S.permissions).forEach(([k,v])=>{let d=document.createElement('label');d.className='memory';d.innerHTML='<span>'+k+'</span><input type="checkbox">';d.querySelector('input').checked=v;d.querySelector('input').onchange=e=>{S.permissions[k]=e.target.checked;save();log('Permission changed',k+': '+e.target.checked)};x.append(d)})}
function msg(role,text){S.messages.push({role,text,time:Date.now()});save();renderMessages();if(role==='nova'&&localStorage.novaAutoSpeak==='1')speak(text)}
function safeCalc(x){if(!/^[0-9+\\-*/().%\\s]+$/.test(x))throw 0;return Function('"use strict";return ('+x+')')()}
function localBrain(t){let q=t.trim();if(/^remember that /i.test(q)){let m=q.replace(/^remember that /i,'').trim();if(m){S.memory.push(m);save();renderMemory();log('Memory added',m);return'I’ll remember that: '+m}}if(/what can you do|capabilities/i.test(q))return'I am Nova. I can chat, remember information, work with local data, calculate, manage tasks and notes, use browser voice, and connect modular adapters for web research, files, vision, GitHub, calendar, email and automation.';if(/^calculate /i.test(q))try{return String(safeCalc(q.slice(10)))}catch{return'Invalid calculation.'};if(/who are you/i.test(q))return'I’m Nova — an independent modular personal AI. My interface, memory, tools and provider layer are separate, so capabilities can grow without replacing my core.';if(/how do you work/i.test(q))return'I use a conversation core, provider adapters, memory, a permissioned tool registry and an activity log. Without a model provider I can still run local tools.';return'Local mode is active. Connect a generative model in Settings for full natural-language answers.'}
async function gemini(t){let context=[...S.messages.slice(-24)].map(m=>({role:m.role==='user'?'user':'model',parts:[{text:m.text}]}));context.push({role:'user',parts:[{text:t}]});let extra='\nKnown memory:\n'+S.memory.join('\n- ')+'\nKnowledge:\n'+S.knowledge.join('\n- ');let body={system_instruction:{parts:[{text:'You are Nova, a helpful personal AI assistant. Be accurate, natural, transparent about limitations, and never claim a tool action happened unless it actually did. Ask for confirmation before consequential external actions.'+extra}]},contents:context};let r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(S.model)+':generateContent?key='+encodeURIComponent(S.key),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('Provider error '+r.status);let j=await r.json();return j.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'No response.'}
async function send(t){t=t.trim();if(!t)return;msg('user',t);$('#input').value='';let r;try{r=S.provider==='gemini'&&S.key?await gemini(t):localBrain(t)}catch(e){r='I could not reach the configured AI provider. '+e.message}msg('nova',r);log('Conversation turn')}
function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=Number($('#rate')?.value||1);speechSynthesis.speak(u)}
function listen(){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){alert('Speech recognition is unavailable in this browser.');return}let r=new R();r.lang='en-IN';r.interimResults=false;r.onresult=e=>{$('#input').value=e.results[0][0].transcript;send($('#input').value)};r.start();log('Voice listening started')}
function download(n,d){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([d],{type:'application/json'}));a.download=n;a.click();URL.revokeObjectURL(a.href)}
function updateClock(){$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
$('#form')?.addEventListener('submit',e=>{e.preventDefault();send($('#input').value)});
$('#new')?.addEventListener('click',()=>{S.messages=[];save();render();log('New conversation')});
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.v)?.classList.add('active');$('#title').textContent=b.textContent.trim()});
$$('[data-prompt]').forEach(b=>b.onclick=()=>send(b.dataset.prompt));
$('#voice')?.addEventListener('click',listen);$('#voiceStart')?.addEventListener('click',listen);$('#voiceLast')?.addEventListener('click',()=>{let m=[...S.messages].reverse().find(x=>x.role==='nova');if(m)speak(m.text)});
$('#remember')?.addEventListener('click',()=>{let v=$('#memIn').value.trim();if(v){S.memory.push(v);$('#memIn').value='';save();renderMemory();log('Memory added',v)}});
$('#exportMemory')?.addEventListener('click',()=>download('nova-memory.json',JSON.stringify(S.memory,null,2)));
$('#saveKnowledge')?.addEventListener('click',()=>{let v=$('#knowledgeIn').value.trim();if(v){S.knowledge.push(v);$('#knowledgeIn').value='';save();renderKnowledge();log('Knowledge added')}});
$('#calcBtn')?.addEventListener('click',()=>{try{$('#calcOut').textContent=safeCalc($('#calc').value)}catch{$('#calcOut').textContent='Invalid expression'}});
$('#noteBtn')?.addEventListener('click',()=>{let v=$('#note').value.trim();if(v){S.notes.push(v);$('#note').value='';save();log('Note saved',v)}});
$('#exportAll')?.addEventListener('click',()=>download('nova-workspace.json',JSON.stringify(S,null,2)));
$('#importAll')?.addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{Object.assign(S,JSON.parse(r.result));save();render();log('Workspace imported')}catch{alert('Invalid workspace file')}};r.readAsText(f)});
$('#fileInput')?.addEventListener('change',e=>{let x=$('#fileList');x.innerHTML='';[...e.target.files].forEach(f=>{let d=document.createElement('div');d.className='memory';d.textContent=f.name+' — '+Math.round(f.size/1024)+' KB';x.append(d)});log('Files staged',e.target.files.length+' file(s)')});
$('#visionFile')?.addEventListener('change',e=>{let f=e.target.files[0],x=$('#visionPreview');if(!f)return;x.innerHTML='';let im=new Image();im.src=URL.createObjectURL(f);im.style.maxWidth='100%';im.style.maxHeight='360px';im.style.borderRadius='14px';x.append(im);log('Image staged',f.name)});
$('#analyzeCode')?.addEventListener('click',()=>{let c=$('#codeIn').value,lines=c?c.split('\n').length:0;$('#codeOut').textContent='Local scan: '+lines+' lines, '+c.length+' characters. Connect Nova to a model/GitHub tool for semantic review.';log('Code analyzed locally')});
$('#addTask')?.addEventListener('click',()=>{let v=$('#taskIn').value.trim();if(v){S.tasks.push({text:v,done:false});$('#taskIn').value='';save();renderTasks();log('Task added',v)}});
$('#clearHistory')?.addEventListener('click',()=>{if(confirm('Clear conversation?')){S.messages=[];save();render();log('Conversation cleared')}});
$('#save')?.addEventListener('click',()=>{S.provider=$('#provider').value;S.key=$('#key').value.trim();S.model=$('#model').value.trim()||'gemini-2.5-flash';localStorage.novaProvider=S.provider;localStorage.novaKey=S.key;localStorage.novaModel=S.model;$('#status').textContent=S.provider==='gemini'?'Gemini connected':'Local mode';log('Provider settings changed',S.provider)});
$('#forget')?.addEventListener('click',()=>{$('#key').value='';S.key='';localStorage.removeItem('novaKey');log('Provider key forgotten')});
$('#resetPermissions')?.addEventListener('click',()=>{S.permissions={web:false,github:false,email:false,calendar:false,automation:false};save();renderPermissions();log('Permissions reset')});
$$('[data-info]').forEach(b=>b.onclick=()=>alert('This module is ready for an adapter. The adapter should declare permissions, execute actions, report results, and pass consequential actions through Nova’s confirmation layer.'));
$('#provider').value=S.provider;$('#key').value=S.key;$('#model').value=S.model;$('#status').textContent=S.provider==='gemini'?'Gemini connected':'Local mode';setInterval(updateClock,1000);render();